### ISSUE TITLE
Error while logging: The security token included in the request is invalid

### ISSUE THREAD

**Issue by khurram72** [Zsmerritt/Flutter_AWS_CloudWatch#7]
Hi,

Whenever I am trying to log some message to AWS Cloudwatch using our temp access key & secret key, the following error is thrown.

``` CloudWatchException - type: UnrecognizedClientException, message: The security token included in the request is invalid. ```

Also, could you please highlight, why the library doesn't have accessToken as a param, and how does it log without token?

I am using the latest version of the library: ```aws_cloudwatch: ^0.4.5```

I have followed the guide as per the Example 3, as in installation guide, still encountering the issue as mentioned.

Your help would be highly appreciated.

Thanks!

@Zsmerritt

**Comment by Zsmerritt** [comment]
An `UnrecognizedClientException: The security token included in the request is invalid.` usually means something is wrong with the AWS credentials. In this particular case thats probably because you're using temporary credentials. Currently only long term credentials which don't require a session token are supported as of version 0.4.5.

Fortunately it looks like adding support for temporary credentials is pretty simple. I will push out a new version that supports this feature set in the next day or two.

**Comment by khurram72** [comment]
Thanks for your quick response. It would be really helpful to us as well as anyone else considering using the library for this particular use case.

**Comment by Zsmerritt** [comment]
Give it a shot with 0.4.6 and let me know if that solves your issue
